Item wheel
mkw-sp/mkw-sp pull request #660
Opened 2023-04-02 21:03 UTC by henrymkw

Adds an item wheel option under the debug section so players can practice with items and use save states to practice more efficiently and effectively

2023-04-02 22:23 UTC, henrymkw commented
Just realized a bug where the golden does not go away after using it. Lmk if any one has suggestions to this

2023-04-03 22:19 UTC, stblr requested changes

2023-04-03 22:19 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +    },
These ids are already used in RaceSP.

2023-04-03 22:19 UTC, stblr commented on assets/message/Race_U.bmg.json5
> +    },
This should go in RaceSP.

2023-04-03 22:19 UTC, stblr commented on assets/message/Race_E.bmg.json5
> +    },
Can be dropped.

2023-04-03 22:19 UTC, stblr commented on payload/game/item/KartItem.cc
> +}
```suggestion
#include "game/system/RaceManager.hh"
#include "game/system/SaveManager.hh"
#include "game/util/Registry.hh"

extern "C" {
#include <revolution/kpad.h>
}
#include <sp/cs/RoomClient.hh>
```

2023-04-03 22:19 UTC, stblr commented on payload/game/item/KartItem.cc
> +static bool pressedLastFrame;
Can we avoid making this global?

2023-04-03 22:19 UTC, stblr commented on payload/game/item/KartItem.cc
> +        auto *playerPadProxy = System::RaceManager::Instance()->player(0)->padProxy();
How is multiplayer handled?

2023-04-03 22:19 UTC, stblr commented on payload/game/item/KartItem.hh
> +#include <Common.hh>
```suggestion
#include "game/kart/KartObjectProxy.hh"

#include <Common.hh>
```

2023-04-03 22:19 UTC, stblr commented on payload/game/item/KartItem.hh
> +};
```suggestion
};

```

2023-04-03 22:19 UTC, stblr commented on payload/game/system/GhostFile.hh
> +#include <game/util/Registry.hh>
```suggestion
#include "game/system/Mii.hh"
#include "game/util/Registry.hh"
```

2023-04-03 22:19 UTC, stblr commented on payload/game/system/InputManager.hh
> +
```suggestion
#include "game/util/Registry.hh"

#include <sp/CircularBuffer.hh>
```

2023-04-03 22:19 UTC, stblr commented on payload/game/system/GhostFile.hh
> +    Registry::Controller controllerId : 4;
Tested?

2023-04-03 22:19 UTC, stblr commented on payload/game/system/RaceConfig.cc
> +                scenario.players[i].controllerId = Registry::Controller::WiiWheel; // Wii Wheel
The comment is no longer necessary.

2023-04-03 22:19 UTC, stblr commented on payload/game/system/RaceConfig.hh
> +#include <game/util/Registry.hh>
```suggestion
#include "game/util/Registry.hh"

#include <Common.hh>
```

2023-04-03 22:19 UTC, stblr commented on symbols.txt
> +0x8059c118 _ZN4Kart15KartObjectProxy10cancelBillEv
Ordering.

2023-04-03 22:19 UTC, stblr commented on payload/game/system/SaveManager.hh
> +    bool getItemWheelFlag();
Maybe just make it a public field?

2023-04-03 22:25 UTC, henrymkw commented on payload/game/item/KartItem.cc
> +static bool pressedLastFrame;
Add a field to KartItem?

2023-04-03 22:27 UTC, stblr commented on payload/game/item/KartItem.cc
> +static bool pressedLastFrame;
Yeah, there is maybe some padding that we can use.

2023-04-03 22:27 UTC, henrymkw commented on payload/game/item/KartItem.cc
> +        auto *playerPadProxy = System::RaceManager::Instance()->player(0)->padProxy();
Its not, I considered this for offline in time trials. If you want me to make it a multiplayer thing, I can do that, but I don't know how practical that would be

2023-04-03 22:29 UTC, stblr commented on payload/game/item/KartItem.cc
> +        auto *playerPadProxy = System::RaceManager::Instance()->player(0)->padProxy();
That's not needed, I just want to be sure that there are no side effects in other gamemodes/configurations.

2023-04-03 22:44 UTC, henrymkw commented on assets/message/MenuSP_U.bmg.json5
> +    },
They should have different IDs but remain in the same file right?

2023-04-03 22:45 UTC, henrymkw commented on assets/message/Race_U.bmg.json5
> +    },
Different ID and different file?

2023-04-03 22:47 UTC, henrymkw commented on payload/game/system/GhostFile.hh
> +    Registry::Controller controllerId : 4;
I tested all controllers but can't remember if that was before or after I changed the type so I'll test again later

2023-04-04 01:27 UTC, henrymkw commented on payload/game/system/SaveManager.hh
> +    bool getItemWheelFlag();
For some reason making it a public field in SaveManager causes it to crash on boot (check the images I sent to discord earlier of the errors I got). No idea why but something doesn't seem right

2023-04-04 03:26 UTC, riidefi commented on payload/game/item/KartItem.cc
> +            m_inventory.currentItemID == Item::Golden && m_inventory.framesLeft != 0x1c2) {
Use decimal

2023-04-04 03:27 UTC, riidefi commented on payload/game/item/KartItem.cc
> +    if (gameMode == System::RaceConfig::GameMode::TimeAttack && m_inventory.framesLeft == 0x1c2) {
decimal

2023-05-25 23:50 UTC, henrymkw commented on payload/game/system/SaveManager.hh
> +    bool getItemWheelFlag();
Tried again today and same issue. I don't know how offsets work in C++ as far as private/public fields go, but I assume that they're different offsets.

2023-05-26 00:01 UTC, riidefi requested changes
Nice work! I've included a few suggestions

2023-05-26 00:01 UTC, riidefi commented on payload/game/system/InputManager.cc
> +    if (auto saveStateManager = SP::SaveStateManager::Instance()) {
auto* saveStateManager

2023-05-26 00:01 UTC, riidefi commented on payload/game/system/InputManager.cc
> +    if (auto saveStateManager = SP::SaveStateManager::Instance()) {
auto* saveStateManager

2023-05-26 00:01 UTC, riidefi commented on payload/game/system/InputManager.cc
> +    if (auto saveStateManager = SP::SaveStateManager::Instance()) {
auto* saveStateManager

2023-05-26 00:01 UTC, riidefi commented on payload/game/system/SaveManager.cc
> +    if (m_usedItemWheel == true) {
```diff
- if (m_usedItemWheel == true) {
+ if (m_usedItemWheel) {
```

2023-05-26 20:28 UTC, stblr commented on payload/game/system/SaveManager.hh
> +    bool m_usedItemWheel;                               // Added
```suggestion

public:
    bool m_usedItemWheel;                               // Added
```

2023-05-29 22:59 UTC, riidefi requested changes

2023-05-29 22:59 UTC, riidefi commented on payload/game/item/KartItem.cc
> +            }
Can we pull this into its own function?

2023-05-29 22:59 UTC, riidefi commented on payload/game/scene/RaceScene.cc
> +    auto saveManager = System::SaveManager::Instance();
auto*

2023-05-29 22:59 UTC, riidefi commented on payload/game/system/SaveManager.cc
> +bool vsSpeedModIsEnabled;
What is the purpose of this?

2023-05-29 23:13 UTC, henrymkw commented on payload/game/system/SaveManager.cc
> +bool vsSpeedModIsEnabled;
Like I said in discord I have a skill issue and have no idea how that got there. Will fix tomorrow and see if there is any other instances of this

2023-05-29 23:49 UTC, vabold requested changes

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.hh
> +    None = 0xFF,
Enum classes are compiled as 32-bit integers. `None` should go at the top with a definition of `-1`.

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.cc
> +Items ItemInventory::getItem() {
```suggestion
Items ItemInventory::currentItem() const {
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.cc
> +bool ItemInventory::getPressed() {
```suggestion
bool ItemInventory::getPressed() const {
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.hh
> +enum class Items {
```suggestion
enum class ItemId {
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.hh
> +    u32 m_currentItemCount;
```suggestion
    s32 m_currentItemCount;
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/ItemInventory.hh
> +    u8 _2b[0x2c - 0x2b];
This math seems wrong. `u8 _0c[0x28 - 0x0c];` implies the bool is at field 0x28, whereas `u8 _2b[0x2c - 0x2b];` implies the bool is at field 0x2a. The static assert is still fine because of the implicit padding in the class.

2023-05-29 23:49 UTC, vabold commented on payload/game/item/KartItem.cc
> +                break;
```suggestion
            case Items::Green:
            case Items::NoItem:
                nextItem = Items::Shroom;
                break;
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/KartItem.cc
> +        if (updateItem && !m_inventory.getPressed()) {
```suggestion
        if (!updateItem) {
            m_inventory.setPressed(false);
        } else if (!m_inventory.getPressed()) {
```

2023-05-29 23:49 UTC, vabold commented on payload/game/item/KartItem.hh
> +    REPLACE void update();
We typically use `calc` to refer to functions which are called once per frame.

2023-05-29 23:49 UTC, vabold commented on payload/game/system/SaveManager.cc
> +    }
Is `SaveManager` the best place for this field? This is perhaps better suited in the Item namespace somewhere (possibly `ItemDirector`, as it appears to have padding bytes).

2023-05-29 23:49 UTC, vabold commented on payload/game/util/Registry.cc
> +bool isControllerValid(Controller controller) {
```suggestion
bool IsControllerValid(Controller controller) {
```

2023-05-29 23:49 UTC, vabold commented on payload/sp/SaveStateManager.cc
> +        if (m_framesHeld <= 60) {
What does this change do?

2023-05-30 13:26 UTC, henrymkw commented on payload/game/system/SaveManager.cc
> +    }
I think SaveManager makes most sense since it is responsible for saving saving ghosts.

2023-05-31 18:03 UTC, riidefi commented on payload/game/item/KartItem.cc
> +    return itemCycle.front();
```diff
- *it != itemCycle.back()
+ it != itemCycle.begin() + (itemCycle.size() - 1)
```

2023-05-31 18:06 UTC, riidefi commented on payload/sp/SaveStateManager.cc
> +        if (m_framesHeld <= 60) {
Can this be splintered off this PR? We should probably add this at some point, but it doesn't make sense for this (orthogonal) feature to block the itemwheel PR.

2023-05-31 18:08 UTC, riidefi commented on payload/game/item/ItemInventory.hh
> +    bool getPressed() const;
If this is only used for the item wheel, perhaps a more descriptive name would make more sense? e.g. `ItemWheelCooldown`

2023-05-31 18:08 UTC, riidefi commented on payload/game/scene/RaceScene.cc
> +    saveManager->m_usedItemWheel = setting == SP::ClientSettings::ItemWheel::Enable;
Would it not make more sense to set this flag when the itemwheel is actually activated?

2023-05-31 18:09 UTC, riidefi commented
Other than those suggestions, I think this is good to merge.

2023-05-31 18:35 UTC, henrymkw commented on payload/game/scene/RaceScene.cc
> +    saveManager->m_usedItemWheel = setting == SP::ClientSettings::ItemWheel::Enable;
This is already in the pr (in saveManager.setSetting() or something like that). I can test this out but I think this is needed since we can’t guarantee the setting is off when a race is started or that a user won’t change a setting mid race

2023-05-31 18:36 UTC, riidefi commented on payload/game/scene/RaceScene.cc
> +    saveManager->m_usedItemWheel = setting == SP::ClientSettings::ItemWheel::Enable;
By "activated" I meant when the user is given a new item by the itemwheel code after triggering it with a button press.

2023-06-01 13:12 UTC, henrymkw commented on payload/sp/SaveStateManager.cc
> +        if (m_framesHeld <= 60) {
Would this actually block the PR? I can remove it if so (and maybe my related code in InputManager?) and make another PR regarding this. But this one character change has made practicing strats over and over super easy so I definitely want to keep it.

2023-06-01 13:18 UTC, GnomedDev commented on payload/sp/SaveStateManager.cc
> +        if (m_framesHeld <= 60) {
It was originally how you are changing it back to, but some dev chat on 26/02/2023 made me decide to change it to how it is now, primarily to allow for saving as soon as you get into a situation. But overall, this should be fixed by configurable controls. 

I recommend just reverting this back to how it is on main.

2023-06-01 14:43 UTC, henrymkw commented
Items don't pop out of the item window when used and it will take some time for me to RE. IMO, getting this to work is more work than its worth and I am fine without this in the PR.

2023-06-01 14:50 UTC, Unnamed1242 commented
Is this not intended by an item wheel? Of course you can make them pop out again, but that's not a must, is it? Most of the item wheel gecko codes work similar (without popping).

2023-06-01 14:53 UTC, henrymkw commented on payload/sp/SaveStateManager.cc
> +        if (m_framesHeld <= 60) {
That's fair, I'll change it back. Do you guys suggest I revert my InputManager changes as well? 
Configurable controls would be dope and would solve a lot of potential problems. Perhaps later down the line another setting can be added to give users the option of whether they want to tap/hold for states.

2023-08-08 04:50 UTC, riidefi approved these changes

2023-08-08 04:52 UTC, merged