Rewrite unnecessary KartMove ASM patches
mkw-sp/mkw-sp pull request #735
Opened 2023-05-14 18:57 UTC by GnomedDev

I can't be bothered to decomp the rest as they are large so we still have to have some ASM patches.

2023-06-17 17:32 UTC, stblr requested changes

2023-06-17 17:32 UTC, stblr commented on payload/game/kart/KartMove.cc
> +    m_hardSpeedLimit = 145 * g_speedModFactor;
```suggestion
    m_hardSpeedLimit = 145.0f * g_speedModFactor;
```

2023-06-17 17:32 UTC, stblr commented on payload/game/kart/KartMove.cc
> +    m_hardSpeedLimit = 120 * g_speedModFactor;
```suggestion
    m_hardSpeedLimit = 120.0f * g_speedModFactor;
```

2023-06-17 17:32 UTC, stblr commented on payload/game/kart/KartMove.hh
> +    REPLACE void restoreBulletSpeedLimit();
These names are confusing.

2023-06-17 17:32 UTC, stblr commented on payload/game/kart/KartMove.cc
> +}
Looking at 8059b7b8, we can maybe drop this.

2023-06-17 17:34 UTC, GnomedDev commented on payload/game/kart/KartMove.hh
> +    REPLACE void restoreBulletSpeedLimit();
Would `restoreNormalSpeedLimit` be cleaner? Or what do you suggest otherwise?

2023-06-20 21:10 UTC, stblr commented on payload/game/kart/KartMove.hh
> +    REPLACE void restoreBulletSpeedLimit();
Something that makes it clear that these functions are a pair like `applyBulletSpeedLimit`/`unapplyBulletSpeedLimit`.

2023-06-21 19:22 UTC, stblr approved these changes

2023-06-21 19:22 UTC, merged