[WIP] Debug course folder
mkw-sp/mkw-sp pull request #802
Opened 2023-06-01 10:27 UTC by riidefi

2023-06-02 14:03 UTC, riidefi commented
Renamed as "Add `/trackmenu` command." Depends on #810.

2023-06-02 17:25 UTC, GnomedDev requested changes
As said on discord, since this is a debugging option that is already using the commands system, it should just be a simple command of `/tracktest path slot music`. This menu is out of place and a maintenance burden.

2023-06-02 23:11 UTC, riidefi commented
Thank you for sharing your perspective on this matter, and I genuinely appreciate the time and thought you put into it. However, in the current context, our focus is not oriented towards integrating such functionality into the command system. While your idea does have its merits, it requires a broader discussion and more substantial development implications than we are prepared to address at this point in time. I hope you understand our position.

I believe the code in my PR is comprehensive and robust, ready to withstand rigorous examination. It's already valuable to anyone who is testing tracks. Far from posing a maintenance challenge, the code operates in an optimal manner, effectively addressing all intended requirements.

2023-06-02 23:23 UTC, vabold commented
Please use LayoutUIControls and other existing infrastructure to handle selection.

2023-06-03 00:47 UTC, riidefi commented
> Please use LayoutUIControls and other existing infrastructure to handle selection.

Fixed in commit bcf2403

2023-06-03 03:02 UTC, riidefi commented
Should be reviewable commit-by-commit.

2023-06-06 07:28 UTC, GnomedDev requested changes

2023-06-06 07:28 UTC, GnomedDev commented on payload/game/ui/page/CourseDebugPage.cc
> +        "DirEntryRange is not an STL-compatible input range");
This should be split off into a separate PR, and kept in it's own header.

2023-06-06 07:28 UTC, GnomedDev commented on assets/control/anim/CourseDebug.brlan.json5
> +}
Newline either here, or remove the one at the end of the brlyt.

2023-06-06 07:40 UTC, riidefi commented on payload/game/ui/page/CourseDebugPage.cc
> +        "DirEntryRange is not an STL-compatible input range");
Sure

2023-06-12 22:43 UTC, GnomedDev commented
This should be set as draft until it is rebased on-top of SP after #827 is merged.

2023-06-12 22:47 UTC, riidefi commented
> This should be set as draft until it is rebased on-top of SP after https://github.com/stblr/mkw-sp/pull/827 is merged.

I appreciate your concern, but Github automatically does that so this is pointless. If stebler merges 827, and then this PR, commit 707812 will be omitted from the history.

2023-07-12 05:32 UTC, riidefi commented
Rebased on top of Gnome's work.

2023-07-16 10:27 UTC, merged

2023-07-16 10:36 UTC, GnomedDev commented
This should not have been merged without anyone's positive review.