Pregenerate course selection
mkw-sp/mkw-sp pull request #805
Opened 2023-06-01 17:39 UTC by GnomedDev

Loosely split from #655. Closes #761.

Also replaces a lot of the usage of u32 and s32 for course ids with the proper enum.

2023-06-01 20:13 UTC, riidefi commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
Move to `CourseIdIsValid`

2023-06-01 20:14 UTC, riidefi commented on payload/game/system/RaceConfig.cc
> +    filter.race = !filter.battle;
{.battle = ..., .race = ... };

2023-06-01 20:15 UTC, riidefi commented on payload/game/system/RaceConfig.cc
> +    filter.race = !filter.battle;
ditto

2023-06-01 20:17 UTC, stblr requested changes

2023-06-01 20:17 UTC, stblr commented on payload/game/system/RaceConfig.cc
> +    }
How is the title screen demo handled?

2023-06-01 20:17 UTC, stblr commented on payload/game/system/RaceConfig.cc
> +        } while (m_courseOrder.contains(randCourse));
What happens if `raceCount` is larger than `courseCount`?

2023-06-01 20:17 UTC, stblr commented on payload/game/ui/SingleTopPage.cc
> +    System::RaceConfig::Instance()->clearCourses();
What about `MultiTopPage`?

2023-06-01 21:45 UTC, GnomedDev commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
uh, do you want me to create a new function for that static_cast or do some extra checks, because extra checks sounds out of scope.

2023-06-01 21:50 UTC, riidefi commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
Do something similar to what hnery did, with a switch case CRS_0 ... CRS_32 essentially

2023-06-01 21:51 UTC, GnomedDev commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
Out of scope for this PR then.

2023-06-01 21:53 UTC, riidefi commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
Retyping `courseId` to an enum would be the out-of-scope change, if any. Notwithstanding, if you want to make that change in this PR, it should be done correctly.

2023-06-01 21:56 UTC, GnomedDev commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
I know it is somewhat out of scope now I've finished it, but started off as a small change to improve type safety. I can split it off into a separate PR if you want, but I don't think we should be making a passable situation worse by adding entirely new validity checking logic.

2023-06-01 22:01 UTC, riidefi commented on payload/game/system/GhostFile.cc
> +    if (static_cast<u32>(header->courseId) >= 0x20) {
I would add this to Registry.cc
```cpp
bool IsControllerValid(Controller controller) {
    switch (controller) {
    case Controller::WiiWheel... Controller::GameCube:
        return true;
    default:
        return false;
    }
}
```
I would expect something like this in any PR that has retyping courseId as a goal

2023-06-01 22:08 UTC, GnomedDev commented on payload/game/system/RaceConfig.cc
> +    }
Good catch, seems like in testing it always does Luigi's circuit, I'll see how to fix.

2023-06-01 22:29 UTC, GnomedDev commented on payload/game/system/RaceConfig.cc
> +        } while (m_courseOrder.contains(randCourse));
Currently it would infinite loop here, how does the base game handle it?

2023-06-01 23:18 UTC, GnomedDev commented on payload/game/system/RaceConfig.cc
> +        } while (m_courseOrder.contains(randCourse));
Looks like the base game doesn't handle this, for battle it generates 10 courses and for race it generates 32 courses.

2023-06-03 19:33 UTC, stblr commented on payload/game/ui/CourseSelectPage.cc
> +        System::RaceConfig::Instance()->clearCourses();
This won't be called if course selection is randomized.

2023-06-03 21:11 UTC, GnomedDev commented on payload/game/ui/CourseSelectPage.cc
> +        System::RaceConfig::Instance()->clearCourses();
It will if it's ordered.

2023-06-04 03:28 UTC, riidefi commented
Would it make more sense to use the arrays in `GlobalContext`? Or if we want, extend GlobalContext with a new array?
| Offset | Name |
|--------|--------|
| GlobalContext+0x78   |  u32 mTrackOrder[32]; | 
| GlobalContext+0xF8   |  u32 mTrackOrderLen; | 
| GlobalContext+0xFC | u32 mBattleOrder[10]; |

| Address | Name |
|----------|--------|
| 808606A4 | GlobalContext_getCourseMatch(u32 index) |
| 808606D0 | GlobalContext_getBattleMatch(u32 index) |

I think the idea would be to keep the course order in `GlobalContext` and let `RaceConfig` stay a mostly dumb POD mostly concerned with the current race?

It seems a bit weird to have `RaceConfig` encroach on `GlobalContext`'s duties like this?

2023-06-04 12:36 UTC, GnomedDev commented
No, because of the reasons I said in the dev channel before you commented that.

2023-06-19 18:59 UTC, riidefi commented
LGTM! I didn't realize we still had SectionManager.c around to complicate things

2023-06-19 18:59 UTC, riidefi approved these changes

2023-06-19 19:38 UTC, GnomedDev commented
Yeah, I was able to very much stub it, but we still need that old-style patch for the GlobalContext allocation.

2023-06-27 23:42 UTC, GnomedDev commented on payload/game/ui/CourseSelectPage.cc
> +        System::RaceConfig::Instance()->clearCourses();
Fixed this, after remembering about the discussion on discord.

2023-07-05 20:11 UTC, GnomedDev commented
Fixed merge conflicts.

2023-07-16 01:23 UTC, merged