Add dummy PackSelectPage
mkw-sp/mkw-sp pull request #807
Opened 2023-06-01 21:16 UTC by GnomedDev

Split from #655. Currently does nothing, gets in the way of getting to a race, and crashes online.

2023-06-11 21:09 UTC, vabold requested changes

2023-06-11 21:09 UTC, vabold commented on payload/game/ui/SingleTopPage.cc
> +    onTAButtonSelect(&m_taButton, 0);
Is this necessary? We already select the button by default in `onInit`.

2023-06-11 21:09 UTC, vabold commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x6A,
OPTIONAL: You can use the extended ID now - this would be preferable in case someone decides to try reimplementing GP mode in the future.

2023-06-11 21:09 UTC, vabold commented on payload/game/ui/SingleTopPage.cc
> +    onBackButtonFront(nullptr, localPlayerId);
Instead of redirecting to a separate handler callback, we should take a page out of `CourseSelectPage` and implement a `onBackCommon` method.

2023-06-11 21:42 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    }
What do you mean "page-dependent"?

2023-06-11 21:43 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +    onTAButtonSelect(&m_taButton, 0);
Without this, when going back from SingleTopPage and to it again, it wouldn't set the model page background correctly.

2023-06-11 21:43 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +    onBackButtonFront(nullptr, localPlayerId);
That's just a waste of lines imo.

2023-06-11 21:45 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +    }
`if (section->isPageActive(PageId::OnlineConnectionManager)) {`

2023-06-11 21:51 UTC, vabold commented on payload/game/ui/SingleTopPage.cc
> +    onTAButtonSelect(&m_taButton, 0);
I understand why we need `onTAButtonSelect` here now, but we do not need a duplicate `selectDefault` call.

2023-06-11 21:54 UTC, vabold commented on payload/game/ui/SingleTopPage.cc
> +    onBackButtonFront(nullptr, localPlayerId);
I'm not sure I agree - I think we would ideally be able to guarantee that the button exists in a button handler.

2023-06-11 21:58 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +    onTAButtonSelect(&m_taButton, 0);
Because otherwise we could hover over battle, then go back to pack select, then to back to single top and the tt model would be shown.

2023-06-12 09:13 UTC, riidefi commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x6A,
This should not be optional

2023-06-12 09:17 UTC, vabold commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x6A,
> This should not be optional

I would consider it optional until all replaced pages are moved to use new IDs.

2023-06-12 10:23 UTC, riidefi commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x6A,
I meant `std::optional`

2023-06-12 18:36 UTC, riidefi commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x100,
Please do not explicitly assign an ID, this will cause merge conflicts.

2023-06-12 18:48 UTC, GnomedDev commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x100,
Will it implicitly be above the 0xFF?

2023-06-12 18:49 UTC, riidefi commented on payload/game/ui/PageId.hh
> +    PackSelect = 0x100,
Yes

2023-06-12 19:01 UTC, stblr requested changes

2023-06-12 19:01 UTC, stblr commented on payload/game/ui/SingleTopPage.cc
Again, please do not forget `MultiTopPage`!

2023-06-12 19:02 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    auto packCount = 1 - Section::HasOnlineManager(sectionId);
Hide the "Nintendo Tracks" pack on online, since online has Nintendo WWs as a separate option to track packs.

2023-06-12 19:18 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +    auto packCount = 1 - Section::HasOnlineManager(sectionId);
Speaking of online, selecting it instantly crashes.

2023-06-12 19:33 UTC, riidefi commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
```diff
- bool isOnline = Section::HasOnlineManager(sectionId);
- u32 packCount = 1 - isOnline;
+ u32 packCount = 1;
+ if (Section::HasOnlineManager(sectionId)) {
+     // Hide the "Nintendo Tracks" pack on online, since online has Nintendo WWs as a separate
+     // option to track packs.
+     packCount = 0;
+ }
```

2023-06-12 19:41 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
I think it's fine as is. We don't want to explicitly set the `packCount` to 0 because in a full implementation, 1 is only a placeholder value.

2023-06-12 19:42 UTC, riidefi commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
I disagree

2023-06-12 19:44 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
I disagree with rii

2023-06-12 19:45 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
Maybe `packCount--;`, but not `packCount = 0;`.

2023-06-12 19:46 UTC, riidefi commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
```diff
- bool isOnline = Section::HasOnlineManager(sectionId);
- u32 packCount = 1 - isOnline;
+ u32 packCount = 1;
+ if (Section::HasOnlineManager(sectionId)) {
+     // Hide the "Nintendo Tracks" pack on online, since online has Nintendo WWs as a separate
+     // option to track packs.
+     --packCount;
+ }
```

2023-06-12 21:43 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
What happened to "if the PR is an improvement to SP, merge it"

2023-06-12 22:37 UTC, riidefi commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
You're right. The quote was
> "does this PR improve the code's quality", and when the answer is "yes, it is better in this state than in the previous state", it should be merged 

...in the context of refactoring. My suggestion undoubtedly improves the quality of your code, and therefore should be applied.

2023-06-13 09:12 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1 - isOnline;
Resolved in https://github.com/stblr/mkw-sp/pull/807/commits/fbfa7a5159f42d0a28699dbe75a927d8d3e25645

2023-06-13 09:13 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    auto packCount = 1 - Section::HasOnlineManager(sectionId);
Explained in https://github.com/stblr/mkw-sp/pull/807/commits/fbfa7a5159f42d0a28699dbe75a927d8d3e25645

2023-06-13 09:13 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    auto packCount = 1 - isOnline;
Resolved in https://github.com/stblr/mkw-sp/pull/807/commits/fbfa7a5159f42d0a28699dbe75a927d8d3e25645

2023-06-13 10:41 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
Resolved

2023-06-19 21:37 UTC, stblr requested changes

2023-06-19 21:37 UTC, stblr commented on payload/game/ui/PackSelectPage.cc
> +std::optional<u32> PackSelectPage::s_lastPackFront = std::nullopt;
Looks like this is never changed.

2023-06-19 21:37 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +    "10394": {
It avoids confusion when talking about a particular message id. The previous ones will also have to be changed.

2023-06-19 21:37 UTC, stblr commented on payload/game/ui/page/ControllerBoxesPage.hh
> +class ControllerBoxesPage : public Page {
If you care, the name of this page certainly starts with PlayerPad.

2023-06-19 21:37 UTC, stblr commented on payload/game/ui/Section.cc
> +        return new PackSelectPage;
Should go at the end since this is sorted by page id.

2023-06-20 09:42 UTC, GnomedDev commented on assets/message/MenuSP_U.bmg.json5
> +    "10394": {
I don't believe that is a worthwhile tradeoff for more conflicting happening when modifying these files (especially if not implemented with a tidy check). Anyway, discussion on this should happen on it's own issue/PR if you are going to implement this.

2023-06-20 09:49 UTC, GnomedDev commented
Fixed comments

2023-06-21 20:02 UTC, stblr commented
2 issues found when testing:

In single player, when going back to the SingleTopPage, the first button (Time Trials) is always selected.

In multiplayer, when going back to the main menu, the PackSelectPage briefly appears.

2023-06-21 20:51 UTC, GnomedDev commented
The TT button always being reselected is on purpose, since if a pack does not support a mode the button has to be hidden and it seemed like the simplest way, I could remove this and leave this for the real track packs PR to sort out though.

2023-06-21 21:01 UTC, stblr commented
You could easily check for `Anim::Next` in `onActivate`.

2023-06-22 10:34 UTC, GnomedDev commented
Fixed all of that

2023-06-22 21:28 UTC, stblr approved these changes

2023-06-22 21:28 UTC, merged