Implement utils for working with Sha
mkw-sp/mkw-sp pull request #832
Opened 2023-06-13 22:07 UTC by GnomedDev

Split off from #655

2023-06-15 23:25 UTC, riidefi commented
I think this is fine, but the annoying thing with C++ is that a std::array reference isn't like a Rust arrayref, so this code sort of requires that everyone is locked into the Sha1 struct. Perhaps we could provide two aliases? i.e.
```cpp
using Sha1 = std::array<u8, 0x14>;
using Sha1Ref = std::span<u8, 0x14>;
```

2023-06-15 23:26 UTC, GnomedDev commented
Being locked into the `Sha1` struct is mostly the point, for type safety.

2023-06-15 23:44 UTC, riidefi commented
Okay--while I personally think this is quite brittle and odd for a function on a read-only span of 20 bytes requiring the programmer to memcpy them into a specific structure (when reading them a file is a use case), I can agree that the security footguns of the current approach (with a raw pointer) are worse. I've approved this change.

2023-06-15 23:45 UTC, riidefi approved these changes

2023-07-04 23:42 UTC, vabold requested changes

2023-07-04 23:42 UTC, vabold commented on payload/sp/ShaUtil.hh
> +#include <string_view>
```suggestion
#include <expected>
#include <string_view>

#include <Common.hh>
```

2023-07-04 23:42 UTC, vabold commented on payload/sp/ShaUtil.cc
> +#include <vendor/libhydrogen/hydrogen.h>
While you're fixing includes:
```suggestion
#include "ShaUtil.hh"

#include <vendor/libhydrogen/hydrogen.h>
```

2023-07-04 23:56 UTC, GnomedDev commented on payload/sp/ShaUtil.hh
> +#include <string_view>
Huh, that's weird, I could swear it was common before stdlib, but I've gone back and checked and nope. There are probably much more examples in the project of incorrect formatting that a tidy check should really be written for it.

2023-07-04 23:57 UTC, GnomedDev commented
Solved conflicts and header ordering issues.

2023-07-05 00:04 UTC, vabold approved these changes

2023-07-05 00:04 UTC, merged