Allow for screenshots to be taken
mkw-sp/mkw-sp pull request #834
Opened 2023-06-14 02:30 UTC by MikeIsAStar

2023-06-14 11:50 UTC, GnomedDev requested changes
Also, could this be wrapped in a class to stop using statics so liberally? Just one static optional instance and the rest could be members, then you don't need a manual `initialized` flag either.

2023-06-14 11:50 UTC, GnomedDev commented on payload/game/system/GameScene.cc
> +        return REPLACED(setFramerate)(is30FPS);
Unrelated change?

2023-06-14 11:50 UTC, GnomedDev commented on payload/game/system/GameScene.hh
> +    REPLACE void setFramerate(bool is30FPS);
Same

2023-06-14 11:51 UTC, vabold commented on payload/game/system/GameScene.cc
> +        return REPLACED(setFramerate)(is30FPS);
If you think the local variable renaming is an unrelated change, wait until you see the `courseFilenames` scope change.

2023-06-14 12:03 UTC, vabold commented on payload/sp/Screenshot.cc
> +    UI::SectionManager *sectionManager = UI::SectionManager::Instance();
```suggestion
    auto *sectionManager = UI::SectionManager::Instance();
```

2023-06-14 12:03 UTC, vabold commented on payload/game/host_system/RkSystem.cc
> +    EGG::Xfb *xfb = EGG::TSystem::Instance().getXfbManager()->headXfb();
```suggestion
    auto *xfb = EGG::TSystem::Instance().getXfbManager()->headXfb();
```

2023-06-14 12:03 UTC, vabold commented on payload/sp/Screenshot.cc
> +    System::InputManager *inputManager = System::InputManager::Instance();
```suggestion
    auto *inputManager = System::InputManager::Instance();
```

2023-06-14 12:03 UTC, vabold commented on payload/sp/Screenshot.hh
> +#include <egg/core/eggXfb.hh>
Why is this included here instead of in `Screenshot.cc`?

2023-06-14 18:35 UTC, MikeIsAStar commented on payload/game/system/GameScene.cc
> +        return REPLACED(setFramerate)(is30FPS);
> Unrelated change?

Quite so.

2023-06-14 18:35 UTC, MikeIsAStar commented on payload/egg/core/eggColorFader.hh
> +    virtual void vf_04() {}
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:35 UTC, MikeIsAStar commented on payload/game/system/ResourceManager.cc
> +    auto courseFilename = s_courseFilenames[courseId];
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:35 UTC, MikeIsAStar commented on payload/sp/Screenshot.cc
> +static OSThread s_thread;
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:36 UTC, MikeIsAStar commented on payload/sp/Screenshot.cc
> +    UI::SectionManager *sectionManager = UI::SectionManager::Instance();
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:36 UTC, MikeIsAStar commented on payload/game/host_system/RkSystem.cc
> +    EGG::Xfb *xfb = EGG::TSystem::Instance().getXfbManager()->headXfb();
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:36 UTC, MikeIsAStar commented on payload/sp/Screenshot.cc
> +    System::InputManager *inputManager = System::InputManager::Instance();
Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:39 UTC, riidefi commented on payload/egg/core/eggColorFader.hh
> +    enum class Status { Opaque = 0, Hidden = 1, FadeIn = 2, FadeOut = 3 };
Always include a trailing comma to avoid future diff noise.

2023-06-14 18:40 UTC, MikeIsAStar commented on payload/sp/Screenshot.hh
> +#include <egg/core/eggXfb.hh>
```c++
void Capture(EGG::Xfb *xfb);
```

2023-06-14 18:42 UTC, MikeIsAStar commented
> Also, could this be wrapped in a class to stop using statics so liberally? Just one static optional instance and the rest could be members, then you don't need a manual `initialized` flag either.

Resolved by commit [31a2a00](https://github.com/stblr/mkw-sp/pull/834/commits/31a2a00be4883489d1f8403f6bfb10a9cd6dd91f).

2023-06-14 18:53 UTC, riidefi commented on payload/egg/core/eggColorFader.hh
> +    Status m_status;
```diff
+ protected:
+ ~Fader() = default;
```
somewhere since this interface does not have a virtual destructor.

2023-06-14 18:54 UTC, riidefi commented on payload/game/system/ResourceManager.hh
> +    static const char *s_courseFilenames[67];
I think we can make this a `std::array` and just get index-out-of-bounds asserts for free?

2023-06-15 15:35 UTC, vabold requested changes
- The files should be renamed to `ScreenshotManager`.
- Should `SaveTask` be private?

2023-06-15 15:35 UTC, vabold commented on payload/sp/Screenshot.hh
> +    void Draw();
```suggestion
public:
    void calc();
    void draw();

    static ScreenshotManager *CreateInstance(u32 framebufferSize);
    static ScreenshotManager *Instance();
```
Optionally, you can also add `static void DestroyInstance();` to match other singletons in the codebase (regardless of if `DestroyInstance` is ever called).

2023-06-15 18:18 UTC, riidefi commented on payload/sp/Screenshot.cc
> +    s_instance->Init(framebufferSize);
I think it'd be fair to rename "Init" to "AllocInner"

2023-06-15 18:20 UTC, riidefi commented on payload/sp/Screenshot.cc
> +ScreenshotManager *ScreenshotManager::s_instance = nullptr;
Would it make more sense to move [1, 7] et al to this convention, honestly? This is consistent with modern style guides and makes sense--we want this stuff immediately visible and not tucked-away or hidden.

2023-06-16 02:06 UTC, MikeIsAStar commented on payload/egg/core/eggColorFader.hh
> +    enum class Status { Opaque = 0, Hidden = 1, FadeIn = 2, FadeOut = 3 };
Resolved by commit [a1dd710](https://github.com/stblr/mkw-sp/pull/834/commits/a1dd71007289dab65592db544547b810ae206148).

2023-06-16 02:06 UTC, MikeIsAStar commented on payload/egg/core/eggColorFader.hh
> +    Status m_status;
Resolved by commit [a1dd710](https://github.com/stblr/mkw-sp/pull/834/commits/a1dd71007289dab65592db544547b810ae206148).

2023-06-16 02:06 UTC, riidefi approved these changes

2023-06-16 02:08 UTC, MikeIsAStar commented on payload/sp/Screenshot.hh
> +    };
Resolved by commit [a1dd710](https://github.com/stblr/mkw-sp/pull/834/commits/a1dd71007289dab65592db544547b810ae206148).

2023-06-16 02:08 UTC, MikeIsAStar commented on payload/sp/Screenshot.cc
> +    s_instance->Init(framebufferSize);
Resolved by commit [a1dd710](https://github.com/stblr/mkw-sp/pull/834/commits/a1dd71007289dab65592db544547b810ae206148).

2023-06-16 02:10 UTC, MikeIsAStar commented on payload/sp/Screenshot.hh
> +    void Draw();
@stblr deemed this as unnecessary.

2023-06-16 02:15 UTC, MikeIsAStar commented on payload/sp/Screenshot.cc
> +ScreenshotManager *ScreenshotManager::s_instance = nullptr;
I will leave this decision up to @stblr.

2023-06-16 02:18 UTC, MikeIsAStar commented
> * The files should be renamed to `ScreenshotManager`.
> * Should `SaveTask` be private?

Resolved by commit [a1dd710](https://github.com/stblr/mkw-sp/pull/834/commits/a1dd71007289dab65592db544547b810ae206148).

2023-06-17 15:33 UTC, riidefi commented on payload/sp/ScreenshotManager.cc
> +    }
Kind of racist, disable interrupts or preferably move to main thread.

2023-06-17 17:20 UTC, stblr commented on payload/sp/Screenshot.cc
> +ScreenshotManager *ScreenshotManager::s_instance = nullptr;
The order in the cc file should match that of the hh.

2023-06-18 17:05 UTC, MikeIsAStar commented on payload/sp/ScreenshotManager.cc
> +    }
Resolved by commit [6440a2a](https://github.com/mkw-sp/mkw-sp/pull/834/commits/6440a2a105ebc6f1e38c730bed79b6bc41773275).

2023-06-19 00:03 UTC, riidefi commented
In the future maybe we should consider a `Storage::WriteFileAsync` API. This is beyond the scope of this PR, but it seems like a common-enough operation.

2023-06-19 21:21 UTC, stblr requested changes

2023-06-19 21:21 UTC, stblr commented on payload/game/system/ResourceManager.hh
> +    static const char *s_courseFilenames[67];
The naming should be `GetCourseFilename` and `CourseFilenames`.

2023-06-19 21:21 UTC, stblr commented on payload/sp/ScreenshotManager.hh
> +#include <atomic>
Unused?

2023-06-19 23:10 UTC, MikeIsAStar commented on payload/sp/ScreenshotManager.hh
> +#include <atomic>
Resolved by commit [668ec78](https://github.com/mkw-sp/mkw-sp/pull/834/commits/668ec782ef2e0559b0436db12c84da5770cf9e86).

2023-06-19 23:25 UTC, MikeIsAStar commented on payload/game/system/ResourceManager.hh
> +    static const char *s_courseFilenames[67];
Resolved by commit [445dcff](https://github.com/mkw-sp/mkw-sp/pull/834/commits/445dcffd5c0481af99f0159cb68c49e208ae3108).

2023-06-20 03:40 UTC, MikeIsAStar commented on payload/sp/ScreenshotManager.cc
> +    }
Since the method does not have a return value, it may be best to leave the method name unchanged.

2023-06-20 20:56 UTC, stblr approved these changes

2023-06-20 20:56 UTC, merged