Use ResChannelId
mkw-sp/mkw-sp pull request #835
Opened 2023-06-15 13:03 UTC by GnomedDev

Would have called it `ResourceChannelId`, but that is so long it causes the formatter to do line wrapping.

2023-06-15 13:11 UTC, vabold requested changes

2023-06-15 13:31 UTC, GnomedDev commented on payload/game/system/MultiDvdArchive.hh
> +
Resolved in ee0528969b6e3344899b46f81ec439fbaba62b42

2023-06-20 18:24 UTC, stblr commented
What about `ResourceType`?

2023-06-20 18:38 UTC, GnomedDev commented
Sounds like a saner name

2023-06-20 20:02 UTC, GnomedDev commented
Done

2023-06-20 20:05 UTC, riidefi requested changes
Can we move the main definition out of MultiDvdArchive, and then have MultiDvdArchive::Type alias that main definition?

2023-06-20 20:06 UTC, GnomedDev commented
Why?

2023-06-20 20:14 UTC, riidefi commented
For instance in MK7, this is `System::EArchiveID`. I generally think its also consistent to have `UI::PageId` rather than `UI::Page::PageId` or `UI::Section::SectionId`, for instance.

2023-06-20 20:16 UTC, riidefi commented
I also wouldn't object to moving this enum to `Registry`, even.

2023-06-20 20:28 UTC, GnomedDev commented
Done

2023-06-21 19:24 UTC, stblr approved these changes

2023-06-21 19:24 UTC, merged