Implement player count setting
mkw-sp/mkw-sp pull request #850
Opened 2023-06-18 12:41 UTC by GnomedDev

Closes #758, draft as based on #661.

Implements a "total player" setting, instead of a "CPU count" setting, to avoid weirdness when interacting with multiplayer.

This also re-removes the `CPUMode::None` setting, as multiplayer can simply set the player count to the number of local players, or less, allowing it to supersede #841.

2023-06-18 15:23 UTC, Zachruff commented
should this be called "total racers" instead? since i feel like "players" implies human players not CPUs

also "The minimum player count, padded by CPU players." why is it "minimum" isnt it total? and maybe im being weird but I feel like padded is a weird term. Maybe simpler to say "Total number of combined CPU and human racers"

2023-06-18 15:27 UTC, vabold commented
"Minimum" is likely a reference to the fact that it's the lower bound of local players and total players.

"Racer Count" is a good name for the setting, and I think the description can be e.g. "Guarantees at least __ racers in a race."

2023-06-18 15:28 UTC, Zachruff commented
> "Minimum" is likely a reference to the fact that it's the lower bound of local players and total players.
> 
> "Racer Count" is a good name for the setting, and I think the description can be e.g. "Guarantees at least __ racers in a race."

ah yes, this is good way of phrasing it

2023-06-18 15:29 UTC, GnomedDev commented
Yeah, it's minimum as the setting could be set to `2` but with 4 local players, it would still have all 4 local players. That name and description does sound saner though.

2023-06-18 15:31 UTC, GnomedDev commented
Actually, looking at it, I'd have to duplicate the description 12 times to name the player count, or implement new logic in the settings system which I am very adverse to doing.

2023-06-18 15:34 UTC, vabold commented
> Actually, looking at it, I'd have to duplicate the description 12 times to name the player count, or implement new logic in the settings system which I am very adverse to doing.

I think there's a way to format the string with a numerical value.

2023-06-18 15:35 UTC, GnomedDev commented
Sure, but as I said, I'd then have to mess with the settings system for one setting.

2023-06-18 16:38 UTC, GnomedDev commented
Before anyone criticizes "Gamer Count", I would like to redirect blame to Vabold who came up with the idea and repeatedly told me in DMs to commit it.

2023-06-18 16:42 UTC, vabold commented
> Before anyone criticizes "Gamer Count", I would like to redirect blame to Vabold who came up with the idea and repeatedly told me in DMs to commit it.

Strange, I don't remember any of these DMs.

We can use "Player" due to the consistency with teams.

2023-06-19 21:10 UTC, stblr requested changes

2023-06-19 21:10 UTC, stblr commented on payload/game/system/RaceConfig.cc
> +        minPlayerCount = static_cast<u8>(setting);
Is this cast needed?

2023-06-19 21:10 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +    },
Please handle singular/plural like e.g. 10421.

2023-06-19 21:20 UTC, GnomedDev commented on assets/message/MenuSP_U.bmg.json5
> +    },
Ah, I need to make 10435 `players`, but we don't need to care about singular since the setting is minimum `2` racers/players.

2023-06-19 21:20 UTC, GnomedDev commented on payload/game/system/RaceConfig.cc
> +        minPlayerCount = static_cast<u8>(setting);
Ah, not anymore.

2023-06-19 21:22 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +    },
Ah, right.

2023-06-20 09:37 UTC, GnomedDev commented
Fixed conflicts and comments.

2023-06-20 18:25 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +        string: "{arg integer|0 0} players",
Should be "racers"?

2023-06-20 20:07 UTC, GnomedDev commented on assets/message/MenuSP_U.bmg.json5
> +        string: "{arg integer|0 0} players",
Fixed

2023-07-04 23:48 UTC, vabold reviewed
Do we want to use "racer" and "player" separately? I'd like to hear more opinions before merge.

2023-07-05 03:58 UTC, Zachruff commented
> Do we want to use "racer" and "player" separately? I'd like to hear more opinions before merge.

imo racer should be both human and CPUs, whereas player is just humans (since nintendo will refer to people as player 1, player 2, etc... and on the title screen you select "3P" mode for 3 player local for example)

2023-07-16 12:15 UTC, riidefi commented
I think it'd be more natural to use "player" even when not referring to physical humans, e.g. "Player Count" rather than "Racer Count". For instance, when we think of "24 player" mode, we aren't picturing 24 little screens as if the game were for a mosquito.

2023-07-16 13:18 UTC, GnomedDev commented
If I change to player, will this be merged?

2023-07-16 13:23 UTC, riidefi commented
I don't see any other issues--unless @MikeIsAStar has something to say.

2023-07-19 20:24 UTC, merged