Reword settings deletion
mkw-sp/mkw-sp pull request #853
Opened 2023-06-18 19:24 UTC by GnomedDev

Closes #479

2023-06-19 21:39 UTC, stblr requested changes

2023-06-19 21:39 UTC, stblr commented on assets/message/MenuSP_U.bmg.json5
> +        string: "All settings for this licence\n will be removed!\nAre you sure this is okay?"
```suggestion
        string: "All settings for this license\n will be removed!\nAre you sure this is okay?"
```

2023-06-20 09:51 UTC, GnomedDev commented on assets/message/MenuSP_U.bmg.json5
> +        string: "All settings for this licence\n will be removed!\nAre you sure this is okay?"
Fixed

2023-06-20 18:18 UTC, stblr approved these changes

2023-06-20 18:18 UTC, merged