Fix character animation
mkw-sp/mkw-sp pull request #860
Opened 2023-06-20 18:30 UTC by stblr

2023-06-20 18:38 UTC, vabold requested changes

2023-06-20 18:38 UTC, vabold commented on payload/game/ui/CourseSelectPage.cc
> +    }
This seems more appropriately placed in `onActivate` rather than `afterCalc`.

2023-06-20 18:38 UTC, vabold commented on payload/game/ui/page/DriftSelectPage.hh
> +    REPLACE void onInit() override;
Irrelevant change?

2023-07-26 20:44 UTC, riidefi commented
For similar reasons to #860, merging.

2023-07-26 20:44 UTC, merged