RaceConfigScenario extension
mkw-sp/mkw-sp pull request #866
Opened 2023-06-21 08:57 UTC by riidefi

2023-06-21 13:58 UTC, GnomedDev requested changes

2023-06-21 17:02 UTC, vabold requested changes

2023-06-21 17:02 UTC, vabold commented on payload/game/system/RaceConfig.hh
> +    struct Ext {
I second `SPScenario`.

2023-06-21 17:02 UTC, vabold commented on payload/game/system/RaceConfig.hh
>      u8 m_ghostBuffers[2][11][0x2800]; // Modified
We've ensured that it's safe to move the offset of these ghost buffers, right?

2023-06-21 18:31 UTC, riidefi commented on payload/game/system/RaceConfig.hh
>      u8 m_ghostBuffers[2][11][0x2800]; // Modified
Yes. For readability and cache locality reasons it's also good practice to keep important data clustered at the top.

2023-06-21 18:32 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +    struct Ext {
I agree.

2023-06-21 18:38 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +    REPLACE void initRaceScenarioForCredits();
Sure, done.

2023-06-21 18:38 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +    Ext m_spAwards;
I've made the original Scenarios public too.

2023-06-21 18:39 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +}
Do you want me to make another PR for just these? It seemed reasonable to group these together.

2023-06-21 20:46 UTC, GnomedDev commented on payload/game/system/RaceConfig.hh
> +}
I do want you to split it, we shouldn't set the precedent that it's okay to group unrelated changes together.

2023-06-21 20:47 UTC, GnomedDev approved these changes
Once the unrelated changes are split off, LGTM.

2023-06-21 22:23 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +}
Okay, sure, done.

2023-07-04 22:59 UTC, vabold requested changes

2023-07-04 22:59 UTC, vabold commented on payload/game/system/RaceConfig.cc
> +
```suggestion
void RaceConfig::initRace() {
    REPLACED(initRace)();
    m_spRace = m_spMenu;
}

void RaceConfig::initAwards() {
    REPLACED(initAwards)();
    m_spRace = m_spMenu;
    m_spAwards = m_spRace;
}

void RaceConfig::initCredits() {
    REPLACED(initCredits)();
    m_spMenu = m_spAwards;
    m_spRace = m_spMenu;
}
```

This more accurately reflects the base game, so we should likely mirror it with our extended scenarios.

2023-07-05 01:05 UTC, riidefi commented on payload/game/system/RaceConfig.cc
> +
Sure, done

2023-07-05 19:45 UTC, vabold approved these changes

2023-07-05 19:45 UTC, merged