Add infra for loading alternative track paths
mkw-sp/mkw-sp pull request #877
Opened 2023-06-26 11:17 UTC by GnomedDev

Draft as based on #866.

2023-07-05 19:56 UTC, GnomedDev commented
Ready for review.

2023-07-16 01:41 UTC, riidefi requested changes

2023-07-16 01:41 UTC, riidefi commented on payload/sp/storage/DecompLoader.cc
> +    if (raceConfig != nullptr && raceConfig->m_spRace.pathReplacement.m_len != 0) {
This is super messy. Is there anything preventing us pulling the new code out, so DecompLoader doesn't have a circular dependency with the game logic? I'd further prefer if the ThumbnailManager code was also yanked, but I am fine with that being saved for another PR.

2023-07-16 01:42 UTC, riidefi commented
Thanks, and nice work. Only one thing I spotted with the path replacement and then we should be good to merge!

2023-07-16 09:20 UTC, GnomedDev commented on payload/sp/storage/DecompLoader.cc
> +    if (raceConfig != nullptr && raceConfig->m_spRace.pathReplacement.m_len != 0) {
The problem is that the nice patch I did to ResourceManager::loadCourse doesn't work anymore because `ro:/` was patched to not read from the SD, and the track path that loadCourse sets up gets prepended with `ro:/`. 

Other places to patch would require rewriting more of ResourceManager's internals which I'm not too familiar with, or reverting the `ro:/` commit (I don't know which one it is) which would be confusing.

I agree this is ugly, but it is the best place we have right now and has no functional downside.

2023-07-16 09:54 UTC, merged