Branding Update (Save Icon/Banner, Channel, Title Screen)
mkw-sp/mkw-sp pull request #882
Opened 2023-06-29 20:49 UTC by Zachruff

Logo, Save Banner, Save Icon, Title Screens made by Wingcapman
Channel Icon/Banner made by Gabubu

Title screens tested on every region on both Dolphin and Wii U in both 4:3/16:9
New channel installation was tested on PAL Disc -> NTSC-U Dolphin, NTSC-U Disc -> NTSC-U Wii U, NTSC-K Disc -> NTSC-U Wii U
Loading through channel was tested with every disc on NTSC-U Wii U
Save banner, save icon, channel banner/icon were tested on NTSC-U Dolphin/NTSC-U Wii U

In-game update for this has NOT been tested. Everything here was always installed from scratch.

2023-06-29 21:02 UTC, stblr commented
Currently the save banner is untouched when updating the channel, but it is overwritten when updating the dol manually...

2023-07-04 21:56 UTC, vabold requested changes

2023-07-04 21:56 UTC, vabold commented on banner.bin.bak
I don't think this was supposed to be included.

2023-07-05 20:38 UTC, Zachruff commented on banner.bin.bak
Oops, deleted.

2023-07-26 20:57 UTC, merged