Fix PackSelectPage online asset issues
mkw-sp/mkw-sp pull request #883
Opened 2023-06-30 14:23 UTC by GnomedDev

This allow the online UI to load again after #807. It also fixes some other small online UI issues related to track packs.

2023-07-04 20:18 UTC, vabold reviewed
Note that these are just comments that I think will help communication in development. You're free to close them if you want.

2023-07-04 20:18 UTC, vabold commented on payload/game/ui/OnlineTopPage.cc
> +    auto packCount = 1;
I would recommend commenting that this a temporary initialization.

2023-07-04 20:18 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1;
Same here.

2023-07-04 20:20 UTC, vabold requested changes

2023-07-04 20:20 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +        connManager->setTrackpack(buttonIndex + 1);
Based on existing implementation, it seems as though `setTrackpack` is meant to set the global pack ID, but the call here is only local. For example, what happens if we have track packs 2 and 4, but the button index suggests we should be setting track pack 3 (even though we don't have track pack 3)?

2023-07-04 21:24 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +        connManager->setTrackpack(buttonIndex + 1);
There are no stable IDs, so this can't work in practice. I implemented this "track pack" stuff back with the initial matchmaking PR as scaffolding to build around. When we have a pack server and a stable ID system this could be properly fixed.

2023-07-04 21:26 UTC, vabold commented on payload/game/ui/PackSelectPage.cc
> +        connManager->setTrackpack(buttonIndex + 1);
Okay, sounds good. I think we could add a comment to reflect that (we love these here).

2023-07-05 00:00 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +        connManager->setTrackpack(buttonIndex + 1);
I think due to the open nature of #881 and this discussion to link back to if it ever gets mentioned again (which I doubt, seeing it's both my things, online UI and track packs), it wouldn't be worth it to fuss over a comment which would require discussion on where to place.

2023-07-05 00:10 UTC, GnomedDev commented on payload/game/ui/PackSelectPage.cc
> +    u32 packCount = 1;
This is already documented in the top level file comment.

2023-07-05 00:15 UTC, GnomedDev commented on payload/game/ui/OnlineTopPage.cc
> +    auto packCount = 1;
Done

2023-07-05 00:25 UTC, merged