Validate '.tpl' files
mkw-sp/mkw-sp pull request #886
Opened 2023-07-04 03:00 UTC by MikeIsAStar

2023-07-04 20:00 UTC, vabold approved these changes
The purpose of this PR is to prevent pointer writes to file-defined offsets in unwanted parts of memory. It's unclear if we have access to secure file sizes for any given TPL, so I think validating the header like this is fair.

This is a good local security measure and the asserts haven't popped up yet in brief testing. It could theoretically be possible for this offset to not be 0xC and still be a valid TPL, therefore causing false positives. However, this is only a theoretical possibility, and I think it's unlikely this will be the case in the future.

I approve, but I think having another set of eyes on this before merging is a good idea.

2023-07-05 19:43 UTC, riidefi requested changes
Re: Array offset -- this is fine. Doing it properly would require changing the API of TPLBind which is not worth the effort.

2023-07-05 19:43 UTC, riidefi commented on payload/revolution/tpl.cc
> +    assert(tpl->numImageDescriptors > 0);
It should probably remain possible to bind an empty `.tpl` archive.

2023-07-19 06:05 UTC, MikeIsAStar commented on payload/revolution/tpl.cc
> +    assert(tpl->numImageDescriptors > 0);
Resolved by commit [177272f](https://github.com/mkw-sp/mkw-sp/pull/886/commits/177272f28b31d72a9053a482e63ce535ca0bd937).

2023-07-19 06:08 UTC, merged